# Generated by Django 4.2.3 on 2023-10-27 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP_Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ICE', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.IntegerField(unique=True)),
                ('document_date', models.DateField()),
                ('ttc_or_ht', models.CharField(choices=[('TTC', 'TTC'), ('HT', 'HT')], default='TTC', max_length=3)),
                ('document_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('document_payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Letter', 'Letter'), ('Bank Transfer', 'Bank Transfer')], max_length=255)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('DEVIS', 'Devis'), ('BL', 'BL')], default='INVOICE', max_length=10)),
                ('document_client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.app_clients')),
                ('document_created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
