# Generated by Django 4.2.3 on 2023-10-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_app_clients_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_items',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
