# Generated by Django 4.2.3 on 2023-10-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_document_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_clients',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='deposit',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_payment_method',
            field=models.CharField(choices=[('Cash', 'CASH'), ('Cheque', 'CHEQUE'), ('Letter', 'LETTER'), ('Bank_Transfer', 'BANK_TRANSFER')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_status',
            field=models.CharField(choices=[('Unpaid', 'UNPAID'), ('Paid', 'PAID')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('invoices', 'INVOICE'), ('devis', 'DEVIS'), ('bl', 'BL')], default='INVOICE', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='ttc_or_ht',
            field=models.CharField(choices=[('TTC', 'TTC'), ('HT', 'HT')], default=None, max_length=3),
        ),
    ]
